-- 1. What are the details of all cars purchased in the year 2022?
SELECT
	* 
FROM cars C
JOIN SALES S 
ON C.car_id = S.car_id
WHERE YEAR(purchase_date) = 2022;

-- 2. What is the total number of cars sold by each salesperson?
select distinct
	sp.age,
    sp.city,
    sp.name,
    sp.salesman_id,
    count(s.sale_id) as Cars_sold
from sales s
join salespersons sp
on sp.salesman_id = s.salesman_id
group by sp.salesman_id
order by Cars_sold desc;

-- 3. What is the total revenue generated by each salesperson?
select 
	sp.name,
	sum(c.cost_$) as revenue
from salespersons sp
join sales s	
on sp.salesman_id = s.salesman_id
join cars c
on c.car_id =  s.car_id
group by sp.name;
-- 4. What are the details of the cars sold by each salesperson?
select
	c.car_id,
	c.make,
    c.type,
    c.style,
    c.cost_$,
    sp.salesman_id,
    sp.name
from cars c
join sales s 
on c.car_id = s.car_id
join salespersons sp
on sp.salesman_id = s.salesman_id
group by sp.salesman_id,c.car_id;

-- 5. What is the total revenue generated by each car type? 
select
	s.car_id,
	c.type,
    c.make,
	sum(c.cost_$) as Revenue
from cars c
join sales s
on s.car_id = c.car_id
group by s.car_id
order by Revenue desc;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select
	* 
from cars
where car_id in 
	(
		select
			car_id
			pupurchase_date
		from sales
        where year(purchase_date) = 2021 and salesman_id in
			(
				select
					salesman_id
				from salespersons
                where name = 'Emily Wong'
            )
    );

-- 7. What is the total revenue generated by the sales of hatchback cars?
select
	c.style,
	sum(c.cost_$) as Revenue
from cars c
join sales s
on s.car_id = c.car_id
group by s.car_id
having c.style = "Hatchback";

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select
	c.style,
	sum(c.cost_$) as Revenue
from cars c
join sales s
on s.car_id = c.car_id
where c.style = 'SUV' and year(s.purchase_date) = 2022
group by c.style
order by Revenue desc;

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select
	sp.name,
    sp.city,
    count(s.car_id) cnt
from salespersons sp
join sales s
on s.salesman_id = sp.salesman_id
where year(s.purchase_date) = 2023
group by sp.name,sp.city
order by cnt desc limit 1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select
	sp.name,
    sp.age,
    s.salesman_id,
    sum(c.cost_$) as revenue
from salespersons sp
join sales s
on s.salesman_id = sp.salesman_id
join cars c
on c.car_id = s.car_id
where year(s.purchase_date) = 2022
group by s.salesman_id
order by revenue desc
limit 1;